### ISSUE TITLE
HEAD isn't buildable?  ( f7d192c )

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/aws#1]
Maybe it's something I did, but it appears to me that the top of the repo is not buildable:
```
   [Ada]          aws-net-websocket-protocol-rfc6455.adb
   [Ada]          aws-client-http_utils.adb
   [Ada]          aws-server-log.adb
aws-client-http_utils.adb:1369:50: prefix of "IMAGE" attribute must be a type
aws-client-http_utils.adb:1405:50: prefix of "IMAGE" attribute must be a type

   compilation of aws-client-http_utils.adb failed
```
Reference: f7d192c

**Comment by anisimkov** [comment]
I guess you use old GNAT version.
Try GNAT GPL 2016.

**Comment by jrmarino** [comment]
Actually I used GCC 6.1 which is pretty recent.
I think it would be a good idea if AWS is buildable by the latest GCC (if not also GCC 5.4)

**Comment by anisimkov** [comment]
Use GNAT GPL from AdaCore. Ada in GCC build not from AdaCore is not well
tested as I undersand
and AWS is not tested in Ada not from AdaCore for sure.

**Comment by jrmarino** [comment]
Sure AWS is tested in gcc.  It's been built by GCC for years.  I can personally attest to this as I maintain the AWS port in FreeBSD ports collection.

It is my opinion that AdaCore should care about GCC FSF for many reasons (that is a separate discussion).  I think it would directly benefit AdaCore and quality assurance, so it should not be consider charity.   In fact, as the designated maintainer of GCC FSF, Adacore should actually be testing their own software on it (again, in m opinion).

However, consider this issue #1 as a notice that that AWS doesn't build on the current and very recent GCC FSF GNAT.  if this is not consider to be an issue, then your position is clear and we can just advertise AWS as a "GNAT GPL Only" if that is really your position.

FYI, the 2016 branch builds on gcc 6.1 fine.  It's just the head that is busted due to the (debatable) position of using cutting-edge code instead of being more conservative.

Please close the issue if no action will come from this notice.  Thanks.

**Comment by anisimkov** [comment]
On 06/12/2016 11:11 PM, jrmarino wrote:
>
> Sure AWS is tested in gcc. It's been built by GCC for years. I can
> personally attest to this as I maintain the AWS port in FreeBSD ports
> collection.
>
> It is my opinion that AdaCore should care about GCC FSF for many
> reasons (that is a separate discussion). I think it would directly
> benefit AdaCore and quality assurance, so it should not be consider
> charity. In fact, as the designated maintainer of GCC FSF, Adacore
> should actually be testing their own software on it (again, in m opinion).
>
AdaCore is in care of GCC for sure, but could not control the GCC
development completely.
Some GCC development can hert the Ada part and AdaCore can't stop from
build GCC without full Ada compartibility.

I do not want to discuss that, you need to know how to build AWS and you
have an answer.
If you want that all existence GCC binary distribution have to be Ada
compartible,
you should discuss it in some other place.

**Comment by jrmarino** [comment]
To be fair, the answer "AWS is only buildable by GNAT GPL" is not a good answer.

If the user cannot or will not use GNAT GPL, then AWS is no longer an option.
Even if it's buildable today, that means there is no guarantee it will be buildable in the future b/c of the reasons you outline, not unless they are going to accept the risk of being forced to use non-FSF version in the future.  IMO, the proper approach *is* that these products should be formally tested against latest GCC FSF (and I am very familiar with GCC development and I'm not really buying the lack of control story; core GCC developers have an entirely different opinion on this matter).

I would almost prefer a declaration that AWS does not support GCC FSF by design so we can remove it from the repository next summer.  At least that would be clear.

okay, I'll close this issue because it's become philosophical.  The technical issue has been reported and it appears no action will be taken so no point in leaving it open.

**Comment by anisimkov** [comment]
On 2016-06-12 23:30, jrmarino wrote:
>
> To be fair, the answer "AWS is only buildable by GNAT GPL" is not a
> good answer.
>
I would say "Tested on GNAT", i.e. GNAT Pro compilers too, not only GNAT
GPL.
You can improve this, build and test AWS on another compilers and
provide the improvements patch.
Some time ago we supported ObjectAda to build AWS, now the support
discontinued.
>
> If the user cannot or will not use GNAT GPL, then AWS is no longer an
> option.
> Even if it's buildable today, that means there is no guarantee it will
> be buildable in the future b/c of the reasons you outline, not unless
> they are going to accept the risk of being forced to use non-FSF
> version in the future. IMO, the proper approach /is/ that these
> products should be formally tested against latest GCC FSF (and I am
> very familiar with GCC development and I'm not really buying the lack
> of control story; core GCC developers have an entirely different
> opinion on this matter).
>
> I would almost prefer a declaration that AWS does not support GCC FSF
> by design so we can remove it from the repository next summer. At
> least that would be clear.
>
This error was because the GCC you used does not support 'Image
attribute on variable.
I'm not sure is it GNAT dialect or modern new Ada 2012 feature.
It's easy to fix.

**Comment by anisimkov** [comment]
On 2016-06-13 11:19, Dmitriy Anisimkov wrote:
> This error was because the GCC you used does not support 'Image
> attribute on variable.
> I'm not sure is it GNAT dialect or modern new Ada 2012 feature.
> It's easy to fix.
John,

The errors you've faced fixed in AWS. Can you try, please.
I don't have GCC 6.1 installed.
I think such easy incompatibilities should be fixed in AWS.

Regards,

Dmitry Anisimkov.

**Comment by jrmarino** [comment]
yes, I confirm that the trunk branch (commit cee62c1) successfully builds with gcc 6.1.
I didn't realize that there was new code until the previous post.
