### ISSUE TITLE
problems with making documentation

### ISSUE THREAD

**Issue by evanescente-ondine** [AdaCore/aws#12]
=> make build-doc          
=== Build doc
gcc -c -I../src/core -I../src/soap -O0 -o /home/mehdi/essai/aws/docs/build/obj/build.o build.adb
gcc -c -I./ -I../src/core -I../src/soap -O0 -I- -o /home/mehdi/essai/aws/docs/build/obj/aws.o /home/mehdi/essai/aws/src/core/aws.ads
gcc -c -I./ -I../src/core -I../src/soap -O0 -I- -o /home/mehdi/essai/aws/docs/build/obj/aws-default.o /home/mehdi/essai/aws/src/core/aws-default.ads
gcc -c -I./ -I../src/core -I../src/soap -O0 -I- -o /home/mehdi/essai/aws/docs/build/obj/soap.o /home/mehdi/essai/aws/src/soap/soap.ads
gnatbind -aO/home/mehdi/essai/aws/docs/build/obj -I../src/core -I../src/soap -x /home/mehdi/essai/aws/docs/build/obj/build.ali
gnatlink /home/mehdi/essai/aws/docs/build/obj/build.ali -o build/bin/build
make[1]: sphinx-build: Command not found
Makefile:72: recipe for target 'html' failed
make[1]: *** [html] Error 127
Makefile:69: recipe for target 'build-doc' failed
make: *** [build-doc] Error 2

**Comment by TurboGit** [comment]
Yes, as reported in the log above, you're missing the sphinx-build command which comes with the python-sphinx on GNU/Debian.
