### ISSUE TITLE
4 issues related to AWS.Client proxy support

### ISSUE THREAD

**Issue by OCTAGRAM** [AdaCore/aws#16]
AWS.Client has broken proxy support. Mostly in AWS.Client.HTTP_Utils:

First, port must be sent unconditionally, or else there are issues with some proxy software. "CONNECT host:443 HTTP/1.1" as opposed to "CONNECT host HTTP/1.1".

On line 147 replace
`& Port_Not_Default (Connection.Host_URL);`
with
`& ':' & Port (Connection.Host_URL);`

Second, SSL configuration is not being taken into consideration when connection goes through proxy. It makes use of default configuration instead, and default configuration demands unconditionally client certificate which is missing of course, thus any secure connection through proxy fails due to missing cert.pem.

On line 209 replace
`SS : Net.SSL.Socket_Type := Net.SSL.Secure_Client (Sock.all);`
with
`SS : Net.SSL.Socket_Type := Net.SSL.Secure_Client (Sock.all, Connection.SSL_Config);`

(style checks require dividing it into more lines)

Third, SNI is not being sent via proxy. AWS.Net.SSL.Connect sends SNI, but AWS.Net.SSL.Secure_Client does not, and sending SNI is not being exported publicly. Secure_Client should probably be extended with SNI host argument and perform SNI. Maybe Connect code should be moved to Secure_Client, and Connect must invoke Secure_Client to make sure behavior is the same no matter if there are proxies or not.

Forth, SSL session reuse is not implemented for proxies. I do not quite understand this thing. When proxy is being used, it can only be desirable to share sessions going through the same proxy, but deny sharing sessions between different proxies. So maybe disabled session sharing is a good thing.

**Comment by anisimkov** [comment]
I comitted 2 first propsals. For the rest need more investigations.

**Comment by anisimkov** [comment]
3rd issue is fixed

**Comment by anisimkov** [comment]
<<it can only be desirable to share sessions going through the same proxy>>
I think we don't have limit to use same SSL session over different proxies.
But anyway HTTP_Connection is tired to proxy and we can't change it after connection created.

I made a fix but can't check it. If you defined that the session was not reused, maybe you can confirm that it is fixed ?

**Comment by OCTAGRAM** [comment]
Can say little about 4th one, just noted the asymmetry and mentioned it for completeness. Cannot confirm this part.

I had impression that there is some kind of pool like in browser, but seems no.

**Comment by anisimkov** [comment]
Ok. Thank you for the analysis anyway.
Yes we have no connection pooling in AWS.

**Comment by anisimkov** [comment]
OCTAGRAM,

If you don't have any questions, can you close the issue ?
