### ISSUE TITLE
Problem building (debian 9 x64)

### ISSUE THREAD

**Issue by ohenley** [AdaCore/aws#17]
Hi, 
Indications, as how to build, are not working on a Debian 9 "stretch" fresh install. After investigating how to fix the build on my side, I let go as I am no expert in Makefiles. Here are the different outputs:

$ make setup build install
gprbind xoscons.bexch
gnatbind xoscons.ali
gnatgcc -c b__xoscons.adb
gnatgcc xoscons.o -o xoscons
Setup OS specific definitions
Can not generate system tags. The test are disabled
make[1]: *** No rule to make target 'setup'.  Stop.
Makefile:162: recipe for target 'templates_parser_setup' failed
make: *** [templates_parser_setup] Error 2

Then I tried just 

$ make
object directory "/home/ohenley/gnoga-code-1.2b/deps/aws/tools/../.build/x86_64-linux-gnu/release/static/obj/tools/" created
object directory "/home/ohenley/gnoga-code-1.2b/deps/aws/include/zlib/../../.build/x86_64-linux-gnu/release/static/obj/zlib" created for project zlib
library directory "/home/ohenley/gnoga-code-1.2b/deps/aws/include/zlib/../../.build/x86_64-linux-gnu/release/static/lib/zlib" created for project zlib
object directory "/home/ohenley/gnoga-code-1.2b/deps/aws/include/../.build/x86_64-linux-gnu/release/static/obj/include" created for project include
library directory "/home/ohenley/gnoga-code-1.2b/deps/aws/include/../.build/x86_64-linux-gnu/release/static/lib/include" created for project include
object directory "/home/ohenley/gnoga-code-1.2b/deps/aws/ssl/../.build/x86_64-linux-gnu/release/static/obj/ssl" created for project ssl
library directory "/home/ohenley/gnoga-code-1.2b/deps/aws/ssl/../.build/x86_64-linux-gnu/release/static/lib/ssl" created for project ssl
object directory "/home/ohenley/gnoga-code-1.2b/deps/aws/src/../.build/x86_64-linux-gnu/release/static/obj/src" created for project src
library directory "/home/ohenley/gnoga-code-1.2b/deps/aws/src/../.build/x86_64-linux-gnu/release/static/lib/src" created for project src
library directory "/home/ohenley/gnoga-code-1.2b/deps/aws/.build/x86_64-linux-gnu/release/static/lib/aws" created for project aws
exec directory "/home/ohenley/gnoga-code-1.2b/deps/aws/tools/../.build/x86_64-linux-gnu/release/static/tools" created for project tools
tools.gpr:19:06: unknown project file: "../.build/projects/aws_asis"
zlib.gpr:19:06: unknown project file: "../../.build/projects/aws_config"
zlib.gpr:19:06: imported by "/home/ohenley/gnoga-code-1.2b/deps/aws/include/zlib/zlib.gpr"
zlib.gpr:19:06: imported by "/home/ohenley/gnoga-code-1.2b/deps/aws/aws.gpr"
zlib.gpr:19:06: imported by "/home/ohenley/gnoga-code-1.2b/deps/aws/tools/tools.gpr"
zlib.gpr:41:10: warning: no when others for this case construction
zlib.gpr:41:15: unknown package or project "Aws_Config"
zlib.gpr:41:15: variable "zlib_exists" is not a single string
gprbuild: "tools/tools.gpr" processing failed
Makefile:187: recipe for target 'build-native' failed
make: *** [build-native] Error 4

Here is the content of my makefile.setup. Everything looks fine:

prefix=/usr/bin/..
DEFAULT_LIBRARY_TYPE=static
ENABLE_SHARED=true
ZLIB=true
XMLADA=false
ASIS=false
IPv6=false
SOCKET=std
LDAP=false
DEBUG=false
PROCESSORS=0
TARGET=x86_64-linux-gnu
GSOAP=false

Thank you.

**Comment by anisimkov** [comment]
I guess you forgot option --recursive  when "git clone".

**Comment by ohenley** [comment]
Thx for the submodule pointer. 

Some smaller things were to be changed for this repo to properly build and install using its shipped gnatgcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516. 

I listed all the missing steps to proceed flawlessly. Maybe, it would be possible to a) amend the build procedure to account for those or b) leave notes about it in the INSTALL file?

1- git clone --recursive https://github.com/AdaCore/aws.git (because of template parser submodules)
2- Inside aws-server-http_utils.adb, at line 921, Pid : constant Natural := Integer'Max
(0, OS_Lib.Pid_To_Integer (OS_Lib.Current_Process_Id)) should be replaced with Pid : constant Natural := 0; (looks like OS_Lib.Current_Process_Id does not exists in gnatgcc (Debian 6.3.0 20170516)
3- mkdir [aws_root_folder]/template_parser/docs/build/latex and mkdir [aws_root_folder]/docs/build/latex

Else you can close this issue. Thx for your assistance.

**Comment by anisimkov** [comment]
> a) amend the build procedure to account for those

Yes, I see, the notes about --recursive option disappeared somehow in info reorganizations.
We will fix that.

> OS_Lib.Current_Process_Id does not exists in gnatgcc (Debian 6.3.0 20170516)
I don't think we should support all GNAT derived distributions. 
Most guaranteed way is to use GNAT and AWS (GPL or Pro) provided by AdaCore.

> 3- mkdir [aws_root_folder]/template_parser/docs/build/latex 
> and mkdir [aws_root_folder]/docs/build/latex

I did not understand that.

<<Else you can close this issue.>>

I can't. As I can understand the issue can be closed only by author.
