### ISSUE TITLE
warning: license of withed unit "DOM.Core.Nodes" may be inconsistent

### ISSUE THREAD

**Issue by OCTAGRAM** [AdaCore/aws#19]
Experiencing this issue on GNAT 2016 GPL & Linux & XMLAda GPL 2016 & AWS from Git

`root@Debian-85-jessie-64-minimal ~/GNAT2016-PostgreSQL/aws # PATH="/opt/adacore/gnat/2016-PostgreSQL/bin:$PATH" make build
gcc -c -gnat2012 -gnatwcfijkmruv -gnaty3abBcdefhiIklmnoOprstx -g -gnata -gnatVa -gnatQ -gnato -gnatwe -Wall templates_parser-xml.adb
gcc -c -gnat2012 -gnatwcfijkmruv -gnaty3abBcdefhiIklmnoOprstx -g -gnata -gnatVa -gnatQ -gnato -gnatwe -Wall soap-message-xml.adb
templates_parser-xml.adb:33:14: warning: license of withed unit "DOM.Core.Nodes" may be inconsistent
templates_parser-xml.adb:34:09: warning: license of withed unit "DOM.Readers" may be inconsistent
templates_parser-xml.adb:35:19: warning: license of withed unit "Input_Sources.File" may be inconsistent
templates_parser-xml.adb:36:19: warning: license of withed unit "Input_Sources.Strings" may be inconsistent
templates_parser-xml.adb:37:09: warning: license of withed unit "Sax.Readers" may be inconsistent
templates_parser-xml.adb:38:17: warning: license of withed unit "Unicode.CES.Basic_8bit" may be inconsistent
templates_parser-xml.adb:39:17: warning: license of withed unit "Unicode.CES.Utf8" may be inconsistent
soap-message-xml.adb:39:14: warning: license of withed unit "DOM.Core.Nodes" may be inconsistent
soap-message-xml.adb:40:19: warning: license of withed unit "Input_Sources.Strings" may be inconsistent
soap-message-xml.adb:41:09: warning: license of withed unit "Sax.Readers" may be inconsistent
soap-message-xml.adb:42:17: warning: license of withed unit "Unicode.CES.Utf8" may be inconsistent

   compilation of soap-message-xml.adb failed
   compilation of templates_parser-xml.adb failed

gprbuild: *** compilation phase failed
Makefile:187: recipe for target 'build-native' failed
make: *** [build-native] Error 4`

"-gnatwe" forces build to fail. I do not quite understand what is the problem here. I was looking for switch to disable this kind of warning, but as it often happens, one looks for appropriate compiler switches, and they are missing. No obvious way to disable license stuff checks, in particular. Maybe some workaround without gnatwe removal still exists.

**Comment by anisimkov** [comment]
Do you know that GNAT GPL 2017 is available ?

**Comment by OCTAGRAM** [comment]
Yes. It had introduced nothing I am hard waiting for, and the issue does not look like related to compiler version. It more looks like subtle AWS Git vs. downloaded XMLAda GPL package conflict. I will test eventually on 2017 too, it is on one of 6 AWS instances I maintain.

**Comment by TurboGit** [comment]
Yes, probably so. Better to use XML/Ada form GitHub too. And as Dmitriy said better using GNAT GPL 2017 it has lot of bug fixes since 2016, and this does not fall into the "nothing I am hard waiting for" !
