### ISSUE TITLE
Declaring an HTTP_Connection appears to raise a Program_Error on macOS

### ISSUE THREAD

**Issue by esthermations** [AdaCore/aws#193]
Hi, I'm writing a simple app that is using AWS' Client library for HTTP stuff. I've immediately run into an issue -- on macOS, any declaration of an HTTP_Connection appears to raise a Program_Error.

I'm using GNAT Community Edition 2020 for a compiler, and the AWS that is packaged with it.

Example code is here: https://github.com/esthermations/VulgarVelma/blob/master/src/vulgarvelma.adb

It's a really simple program at this point, but it still manages to crash. If I declare and initialise the HTTP_Connection within my procedure, the Program_Error is raised there. Otherwise it's raised within aws-client.adb (line 398).

![image](https://user-images.githubusercontent.com/10289860/104713357-de770980-5777-11eb-9caf-9dd10f0bf7c5.png)

Any assistance or pointers would be much appreciated, I don't really know what else I can do here. Thank you!

**Comment by anisimkov** [comment]
I do not see the HTTP_Connection in https://github.com/esthermations/VulgarVelma/blob/master/src/vulgarvelma.adb example

**Comment by esthermations** [comment]
It is created within the call to AWS.Client.Get, here: https://github.com/AdaCore/aws/blob/master/src/core/aws-client.adb#L399

**Comment by anisimkov** [comment]
could you build the executable with 
grpbuild -P vulgarvelma -bargs -E -cargs -g
run and then decrypt stack trace with
addr2line -e bin/vulgarvelma 0x10.....

**Comment by esthermations** [comment]
Hmm, that's not the exception I'm getting, which is 'finalize/adjust raised exception'. But I need SSL so I'll have to rebuild AWS anyway, thanks for pointing that out. I'll let you know how that goes.

Unfortunately I can't seem to get addr2line happening on my mac, even with `brew install binutils` it's just not in any of my bin folders. It's late for me so I'll pick this up tomorrow and let you know how I go. Thank you!

**Comment by anisimkov** [comment]
The second exception I see is 
raised PROGRAM_ERROR : aws-client.adb:398 finalize/adjust raised exception

**Comment by esthermations** [comment]
This is a separate issue I suppose (sorry) but I'm running into this issue running `make setup SOCKET=openssl`: 

<img width="995" alt="Screen Shot 2021-01-15 at 11 32 30 pm" src="https://user-images.githubusercontent.com/10289860/104730478-3d477d80-578e-11eb-889d-e54c52a70ff6.png">

It ends with `raised raised ADA.IO_EXCEPTIONS.NAME_ERROR : aws-os_lib-tmplt.s: No such file or directory` and compilation fails.

**Comment by anisimkov** [comment]
It is really strange. Looks like your local configuration problem. Do you have gnat/bin at the start of your PATH ?

**Comment by esthermations** [comment]
Ah, no I didn't, it was at the end. Thanks for that, AWS is building now. I'll let you know how it goes with my own built AWS.

**Comment by esthermations** [comment]
Working perfectly now, thanks so much! Seems a weird error I got considering the issue was just I needed to rebuild with SSL, but I'll take it. Thanks again for the help. Solved! 😄

**Comment by anisimkov** [comment]
You Welcome !
