### ISSUE TITLE
Exception not handled by server thread: AWS.NET.SOCKET_ERROR : Send : [32] Broken pipe

### ISSUE THREAD

**Issue by stcarrez** [AdaCore/aws#2]
I'm using AWS on by server (blog.vacs.fr) and from time to time the server thread dies
which end to no server thread being able to serve requests.  The frequency is arround
one death per week on the server which receives more than 10K requests.  The death
occurs as part of a broken pipe that occurs when serving client requests.  The AWS server
is behind an Apache 2.4 front end that does proxying (interestingly I'm using this architecture
for more than 2 years but with Apache 2.2 without any problem).

Fatal error, slot 1 is dead now.

raised AWS.NET.SOCKET_ERROR : Send : [32] Broken pipe
Call stack traceback locations:
0xcb94d5 0xcb9e53 0xb58bdd 0xc1c47d 0xcadd87 0xcaf606 0xb612bd 0xb62474 0x100c546 
0x6d9a8b6046f8 0x6d9a8b132b5b 0xffffffffff$

Fatal error, slot 2 is dead now.

raised AWS.NET.SOCKET_ERROR : Send : [32] Broken pipe
Call stack traceback locations:
0xcb94d5 0xcb9e53 0xb58bdd 0xc1c47d 0xcadd87 0xcaf606 0xb612bd 0xb62474 0x100c546
0x6d9a8b6046f8  0x6d9a8b132b5b 0xffffffffff$

And the addr2line gives the following symbolic traceback:

0xcb94d5 <aws__net__std__raise_exception+325>
0xcb9e53 <aws__net__std__send+355>
0xb58bdd <aws__net__send+189>
0xc1c47d <aws__net__buffered__flush+77>
0xcadd87 <aws__server__http_utils__send__send_data.8632+1191>
0xcaf606 <aws__server__http_utils__send+2726>
0xb612bd <aws__server__protocol_handler+5437>:
0xb62474 <aws__server__lineTB+980>
0x100c546 <system__tasking__stages__task_wrapper+502>

Looking at the AWS server code, the AWS.NET.SOCKET_ERROR exception is handled
in one or two places but it is not handled in a few others, which is not correct.

I have fixed that (see my pull request) and I've been using the fix in production for more than one month and the problem is now fixed for me.

**Comment by TurboGit** [comment]
Thanks, please let us know if this is now fixed so that we can close this ticket. Thanks.

**Comment by stcarrez** [comment]
Hi!

I've been using the fix for 3 weeks now without any problems.
You can close it.
Thanks

**Comment by TurboGit** [comment]
Thanks!
