### ISSUE TITLE
AWS.SMTP.Client.Initialize Secure parameter

### ISSUE THREAD

**Issue by pmunts** [AdaCore/aws#249]
There is no information about how to send an email message over SSL (presumably, Secure => True).

Calling AWS.SMTP.Client.Initialize with Secure => True and subsequently calling AWS.SMTP.Client.Send produces an exception that cert.pem is missing, but there is nothing to indicate what cert.pem is supposed to contain.

I am trying to send email via smtpout.secureserver.net port 465 or smtp.gmail.com port 465.

**Comment by TurboGit** [comment]
> Calling AWS.SMTP.Client.Initialize with Secure => True and subsequently calling AWS.SMTP.Client.Send produces an exception that cert.pem is missing, but there is nothing to indicate what cert.pem is supposed to contain.

cert.pem must contain a valid certificate, see demos and/or documentation.

**Comment by pmunts** [comment]
The problem is that there **are no** demos and/or documentation.  Nothing that specifies what a "valid certificate" is or how to generate one.
