### ISSUE TITLE
Problem build AWS + OpenSSL

### ISSUE THREAD

**Issue by DarthEdward** [AdaCore/aws#29]
OS - CentOS 6.9

gcc --version
gcc (GCC) 7.3.1 20180525 (for GNAT Community 2018 20180524)

Package openssl-1.0.1e-57.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version

Package openldap-2.4.40-16.el6.x86_64 already installed and latest version
Package openldap-devel-2.4.40-16.el6.x86_64 already installed and latest version

Source code: http://mirrors.cdn.adacore.com/art/5b0819e0c7a447df26c27abd

make setup
Bind
   [gprbind]      xoscons.bexch
   [Ada]          xoscons.ali
Link
   [link]         xoscons.adb
Setup OS specific definitions
Can not generate system tags. The test are disabled

makefile.setup:

prefix=//home/edward/app/gnat/bin/..
DEFAULT_LIBRARY_TYPE=static
ENABLE_SHARED=true
ZLIB=true
XMLADA=true
ASIS=false
IPv6=false
SOCKET=openssl
LDAP=true 
DEBUG=false
PROCESSORS=0
TARGET=x86_64-pc-linux-gnu
GSOAP=false

make build 

Setup
   [mkdir]        object directory for project Zlib
   [mkdir]        library directory for project Zlib
   [mkdir]        object directory for project Include
   [mkdir]        library directory for project Include
   [mkdir]        object directory for project SSL
   [mkdir]        library directory for project SSL
   [mkdir]        object directory for project Src
   [mkdir]        library directory for project Src
   [mkdir]        library directory for project AWS
   [mkdir]        object directory for project Tools
   [mkdir]        exec directory for project Tools
Compile
   [Ada]          awsres.adb
   [Ada]          aws_password.adb
...
...
...
   [Ada]          wsdl2aws-wsdl-parser.adb
   [Ada]          wsdl2aws-wsdl-parameters.adb
   [Ada]          wsdl2aws-wsdl-types.adb
Build Libraries
   [gprlib]       z.lexch
   [archive]      libz.a
   [index]        libz.a
   [gprlib]       aws_ssl.lexch
   [archive]      libaws_ssl.a
   [index]        libaws_ssl.a
   [gprlib]       aws.lexch
   [archive]      libaws.a
   [index]        libaws.a
Bind
   [gprbind]      awsres.bexch
   [gprbind]      aws_password.bexch
   [Ada]          awsres.ali
   [Ada]          aws_password.ali
   [gprbind]      templates2ada.bexch
   [Ada]          templates2ada.ali
   [gprbind]      webxref.bexch
   [Ada]          webxref.ali
   [gprbind]      templatespp.bexch
   [Ada]          templatespp.ali
   [gprbind]      wsdl2aws-main.bexch
   [Ada]          wsdl2aws-main.ali
Link
   [link]         awsres.adb
   [link]         aws_password.adb
   [link]         templates2ada.adb
   [link]         webxref.adb
   [link]         templatespp.adb
   [link]         wsdl2aws-main.adb
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__locking__finalizeXnn':
aws-net-ssl__openssl.adb:(.text+0xa09): undefined reference to `DH_free'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__cipher_description':
aws-net-ssl__openssl.adb:(.text+0xd57): undefined reference to `SSL_get_current_cipher'
aws-net-ssl__openssl.adb:(.text+0xd75): undefined reference to `SSL_CIPHER_description'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__free__4':
aws-net-ssl__openssl.adb:(.text+0x10b7): undefined reference to `SSL_free'
aws-net-ssl__openssl.adb:(.text+0x10c0): undefined reference to `BIO_free'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__pending':
aws-net-ssl__openssl.adb:(.text+0x1656): undefined reference to `SSL_pending'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__session_reused':
aws-net-ssl__openssl.adb:(.text+0x16e2): undefined reference to `SSL_ctrl'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__set_session_data':
aws-net-ssl__openssl.adb:(.text+0x2161): undefined reference to `SSL_set_session'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__init_random':
aws-net-ssl__openssl.adb:(.text+0x237d): undefined reference to `RAND_seed'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__verify_callback':
aws-net-ssl__openssl.adb:(.text+0x2464): undefined reference to `SSL_get_ex_data_X509_STORE_CTX_idx'
aws-net-ssl__openssl.adb:(.text+0x246e): undefined reference to `X509_STORE_CTX_get_ex_data'
aws-net-ssl__openssl.adb:(.text+0x2479): undefined reference to `SSL_get_SSL_CTX'
aws-net-ssl__openssl.adb:(.text+0x2484): undefined reference to `SSL_get_verify_mode'
aws-net-ssl__openssl.adb:(.text+0x248f): undefined reference to `X509_STORE_CTX_get_current_cert'
...
...
...
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xdaa): undefined reference to `X509_NAME_get_index_by_NID'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xdbd): undefined reference to `X509_NAME_get_entry'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xdc5): undefined reference to `X509_NAME_ENTRY_get_data'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xdf2): undefined reference to `X509_get_issuer_name'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xe09): undefined reference to `X509_get_serialNumber'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xe58): undefined reference to `ASN1_INTEGER_to_BN'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xe67): undefined reference to `BN_bn2hex'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xef3): undefined reference to `BN_free'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xf65): undefined reference to `i2d_X509'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0xfa2): undefined reference to `i2d_X509'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl-certificate-impl__openssl.o): In function `aws__net__ssl__certificate__impl__get':
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1977): undefined reference to `SSL_get_peer_certificate'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x19ad): undefined reference to `SSL_get_verify_result'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1a36): undefined reference to `X509_free'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl-certificate-impl__openssl.o): In function `aws__net__ssl__certificate__impl__load':
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1dbb): undefined reference to `BIO_s_file'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1dc3): undefined reference to `BIO_new'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1eb4): undefined reference to `BIO_ctrl'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1ecf): undefined reference to `PEM_read_bio_X509'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1ee0): undefined reference to `BIO_free'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x1f6c): undefined reference to `X509_free'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x20df): undefined reference to `X509_free'
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x20e7): undefined reference to `BIO_free'
/home/edward/downloads/aws-gpl-2018-src/.build/x86_64-pc-linux-gnu/release/static/lib/aws/libaws.a(aws-net-ssl-certificate-impl__openssl.o): In function `aws__net__ssl__certificate__impl__status_string':
aws-net-ssl-certificate-impl__openssl.adb:(.text+0x2445): undefined reference to `X509_verify_cert_error_string'
collect2: error: ld returned 1 exit status
gprbuild: link of wsdl2aws-main.adb failed
make: *** [build-native] Error 4

Similar problem is observed on Ubuntu 18.
What am I doing wrong?
Thanks.

**Comment by OCTAGRAM** [comment]
See https://github.com/AdaCore/aws/issues/24#issuecomment-396055875 , try my Ubuntu proposal and respond if it worked for you

**Comment by TurboGit** [comment]
Nothing else to do here, solution in #24, closing.
