### ISSUE TITLE
aws-server.adb compilation fails on Mac

### ISSUE THREAD

**Issue by rogermc2** [AdaCore/aws#319]
Mac mini (2018)
OSX 10.15.7
XCode Version 12.0 (12A7209)

Compilation failed with:
~~~
aws-server.adb:953:23: error: non-local pointer cannot point to local object
~~~
~~~
 aws % make setup build
sed: illegal option -- s
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- s
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Bind
   [gprbind]      xoscons.bexch
   [Ada]          xoscons.ali
Link
   [link]         xoscons.adb
Setup OS specific definitions
Can not generate system tags. The test are disabled
Setup
---------

Compile
   [Ada]          awsres.adb
   [Ada]          aws_password.adb
------------
   [Ada]          aws-resources-streams.adb
   [Ada]          aws-server.adb
   [Ada]          aws-headers-values.adb
   [Ada]          aws-resources.adb
   [Ada]          aws-services-transient_pages-control.adb
   [Ada]          aws-server-status.adb
   [Ada]          aws-default.ads
   [Ada]          aws-net-ssl-rsa_dh_generators.adb
   [Ada]          aws-utils-streams.adb
   [Ada]          aws-templates.ads
   [Ada]          aws-response.adb
   [Ada]          aws-exceptions.ads
   [Ada]          aws-containers-string_vectors.ads
   [Ada]          aws-translator.adb

aws-server.adb:953:23: error: non-local pointer cannot point to local object

   compilation of aws-server.adb failed

gprbuild: *** compilation phase failed
make: *** [build-tools-native] Error 4

~~~

**Comment by TurboGit** [comment]
Probably due to a too old compiler  maybe? What's your GNAT version?

**Comment by rogermc2** [comment]
This problem occurs on both my computers.
This is the other one is osx 10.13.6
xcode Version 10.1

 gnatmake -v

GNATMAKE Community 2021 (20210519)
Copyright (C) 1992-2021, Free Software Foundation, Inc.

**Comment by rogermc2** [comment]
I've also tried compiling AWS-Server.adb separately with the same result.
Is "non-local pointer cannot point to local object" a legitimate error?
If not, is there some way of stopping the error from occurring?

**Comment by rogermc2** [comment]
I found this:

https://stackoverflow.com/questions/48939845/non-local-pointer-cannot-point-to-local-object

Is it relevant?

**Comment by TurboGit** [comment]
I was about to propose you to test Unchecked_Access. If it works it is ok as to me this is a false positive error. And I don't have this issue with more recent compiler.

**Comment by rogermc2** [comment]
Yes,  a false positive error.
It seems to me that S is not actually a local variable but seems so because of renaming? So the access is surely safe.
