### ISSUE TITLE
Request: Create Release Tarballs/Zips

### ISSUE THREAD

**Issue by grochoge** [AdaCore/aws#322]
I tried downloading the latest release linked from the repo page (v22) and found that it could not build since it didn't include the submodule content.

I see there was a .zip for v21 that has the submodule contents, can something similar be done for v22?

**Comment by TurboGit** [comment]
There is no v21 version. The .zip is done automatically by GitHub and indeed do not contain submodules. To build AWS, please use git clone with the `--recurse-submodules` option.
