### ISSUE TITLE
Build Fails With GCC/GNAT 10.3.0

### ISSUE THREAD

**Issue by grochoge** [AdaCore/aws#323]
https://github.com/AdaCore/aws/blob/fbf2f209ea25817859e54220d287eccaf2d6ae61/src/http2/aws-http2-frame.adb#L49

I'm attempting to build on Ubuntu 21.10 using the following dependencies: build-essential git unzip xsltproc liblzma-dev libssl-dev libcurl4-openssl-dev git gnat gprbuild libgnatcoll19-dev

I ran `make SOCKET=openssl setup` which succeeds and `make build` which fails with the following:

```
#10 2.497    [Ada]          aws-http2-hpack-table.adb
#10 2.521    [Ada]          aws-http2-message-list.ads
#10 2.532    [Ada]          aws-http2-stream-set.ads
#10 2.580 aws-http2-frame.adb:49:04: warning: use clause for package "System" has no effect
#10 7.165
#10 7.165    compilation of aws-http2-frame.adb failed
#10 7.165
#10 7.165 gprbuild: *** compilation phase failed
#10 7.166 make: *** [Makefile:188: build-tools-native] Error 4
------
executor failed running [/bin/sh -c make build]: exit code: 2
```

**Comment by TurboGit** [comment]
Probably an incompatibility between the GCC/GNAT compiler and the AWS version.

**Comment by grochoge** [comment]
I'm assuming that GCC version is better at detecting unnecessary use clauses. Looking at the .gpr it doesn't seem like it should treat that as an error unless targeting a debug library; which it doesn't seem like the make command should be doing by default. I have yet to look into that more.
