### ISSUE TITLE
Alire crate depends on "gnat_native" when any "gnat" of the correct version would do

### ISSUE THREAD

**Issue by andrewathalye** [AdaCore/aws#364]
My target system does not use glibc, so the version of gnat provided by "gnat_native" wouldn't actually work. It does however have a usable "gnat_external" 12.2.1, so if the crate were changed to simply depend on gnat that would be very helpful.

**Comment by Fabien-Chouteau** [comment]
Hi @andrewathalye, you are right. I opened a PR to change this: https://github.com/alire-project/alire-index/pull/795
