### ISSUE TITLE
How build and install aws with GNAT 2016 in windows 10

### ISSUE THREAD

**Issue by yunushkin88** [AdaCore/aws#4]
Good afternoon. Please tell what I'm doing wrong. I installed GNAT 2016 in windows10. copied this repository to the desktop, opened as it is written build.cmd and run

build C:\GNAT\2016, further the console wrote 

C:\Users\...\Desktop\aws-gpl-2016-src\win32>build 
C:\Users\...\Desktop\aws-gpl-2016-src
The system cannot find the path specified.
gprbuild.exe: project file "config\setup" not found in .;;C:\GtkAda\lib\gnat
Couldn't build or install AWS 

what happened and how can I fix it?

**Comment by yunushkin88** [comment]
It turns out to build the project of the aws in windows 10 need gprbuild [<proj> .gpr] [switches] [names] {[-cargs opts] [-cargs: lang opts] [-largs opts] [-gargs opts]} and if need to build a separate project aws example  hello server also use gprbuild all ways

**Comment by plestedr** [comment]
Don't know if this helps but AWS is built in to the Gnat GPL 2016 package on libre.adacore.com. If you want to experiment there are some example programs in that package as well.

I had better luck last year using the Unix version to compile and run, and using a windows computer to run an internet browser. Didn't have much luck trying to run the AWS examples on my Windows computer.

**Comment by yunushkin88** [comment]
So I put the Gnat 2016, and did according to the instructions on the AWS http://docs.adacore.com/aws-docs/aws/
Could you tell me more like you got run aws example (any OS), simply vebsoket( for example. I tried to run through GPS GPR project but the project was empty. in the same document states that the VSC++, I set Visual Studio and QT, not build.Cygwin have not tried it but it is not the floor etc.  Maybe need to install something else besides just GNAT 2016.
And you did not try to run something for STM32 board microcontroller port and not just the finished project to flash? Simply, he is also not clear how to run)

**Comment by plestedr** [comment]
Well, maybe I spoke too soon. I don't see the examples in the 2016 version that used to exist under the 2015 version. 

I tried to build the hello_world.gpr in the aws repository and ran in to a few issues. I'll play with those before I report them as issues.

Bob

**Comment by yunushkin88** [comment]
Yes, this is the problem for me. Probably should collect gprbuild aws if you run it in the root folder avs.gpr but it requires zlib object and even if the copy zlib still does not compile. Well, actually how to start the project without the  "with aws"  I do not know till.

**Comment by yunushkin88** [comment]
I ran to the ubuntu-16.04.1-desktop-amd64 example hello WORLD's using this guide http://thomaslockerambling.blogspot.ru/2013/09/ada-programming-on-slackware.html

**Comment by plestedr** [comment]
In your original message, I'm not sure if you started the build from the aws directory or inside the win32 directory. There's a file named INSTALL in the aws directory and it has some instructions. I have the gnat system installed in c:\gnat\2016 and you probably do as well. 
Starting in the aws directory....

win32\build.cmd c:\gnat\2016

will build some libraries and put them back in the gnat directory structure. However, before you do that, look in the aws\demos directory. Lots of demos there. Try hello_world one first. Also, you will probably learn more using gps to open the .gpr files and follow the code around. 

Bob

**Comment by yunushkin88** [comment]
And that's it! And I ran into  win32 folder. Yes I agree then it's simple). I just do not understand correctly, thank you very much!)

**Comment by plestedr** [comment]
Hey Dmitri can you go back to the AdaCore/aws repository on github and close this issue. That way new issues get more attention. I am assuming that you are happy with the resolution of this issue.

Thanks, 
Bob
