### ISSUE TITLE
Uninitialized variables in aws-status.adb

### ISSUE THREAD

**Issue by JoDa-Itec** [AdaCore/aws#5]
When I compiled AWS with compiler switch -Wall (using GNAT Pro 17.0w (20160628-49)) I get the following warning:

C:\work\trunk\source\General\External\aws\aws-status.adb: In function 'AWS.STATUS.PREFERRED_CODING':
C:\work\trunk\source\General\External\aws\aws-status.adb:686:7: warning: 'NEXT_ENCODING' may be used uninitialized in this function [-Wmaybe-uninitialized]
C:\work\trunk\source\General\External\aws\aws-status.adb:682:41: warning: 'NEXT_QVALUE' may be used uninitialized in this function [-Wmaybe-uninitialized]

Should these variables be initialized like this?
      Next_Encoding : Messages.Content_Encoding := Messages.Identity;
      Next_QValue : Float := 1.0;

Regards,
Jorg

**Comment by JoDa-Itec** [comment]
According to Adacore these are false positives:

Both are false alarm as the values are only read here:

      if Supported and then Next_QValue > Best_QValue then
         Best_Encoding := Next_Encoding;
      end if;

And they are read only if Supported is true. And when this is the case both variables have been initialized:

         begin
            Next_Encoding := Messages.Content_Encoding'Value (Item);
            Next_QValue   := 1.0; --  Default qvalue
            Supported     := True;

Jorg

**Comment by yunushkin88** [comment]
Hello I'm sorry but you do not tell me how the hell you have installed the web server on Linux or Win I have done according to the instructions here http://docs.adacore.com/aws-docs/aws/building_aws.html bu to this does not work for a week)
