### ISSUE TITLE
building on Linux Centos 6.3 with GNUTLS 2.8.5

### ISSUE THREAD

**Issue by eqcola** [AdaCore/aws#64]
Hi,
i've tried to compile AWS on Centos 6.8  kernel 2.6.32 (x86_64) with GNAT 2018  and GNUTLS 2.8.5.
I've got error on wrapper.c  
`/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:37:12: error: 'GNU
TLS_SEC_PARAM_INSECURE' undeclared here (not in a function); did you mean '_AWS_GNUTLS_SEC_PARAM_INSECURE'?
 AWS_EXPORT(GNUTLS_SEC_PARAM_INSECURE);
            ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:35:25: note: in de
finition of macro 'AWS_EXPORT'
    const int _AWS_##c = c;
                         ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:38:12: error: 'GNU
TLS_SEC_PARAM_EXPORT' undeclared here (not in a function); did you mean '_AWS_GNUTLS_SEC_PARAM_EXPORT'?
 AWS_EXPORT(GNUTLS_SEC_PARAM_EXPORT);
            ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:35:25: note: in de
finition of macro 'AWS_EXPORT'
    const int _AWS_##c = c;
                         ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:39:12: error: 'GNU
TLS_SEC_PARAM_VERY_WEAK' undeclared here (not in a function); did you mean '_AWS_GNUTLS_SEC_PARAM_VERY_WEAK'?
 AWS_EXPORT(GNUTLS_SEC_PARAM_VERY_WEAK);
            ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:35:25: note: in de
finition of macro 'AWS_EXPORT'
    const int _AWS_##c = c;
                         ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:40:12: error: 'GNUTLS_SEC_PARAM_WEAK' undeclared here (not in a function); did you mean '_AWS_GNUTLS_SEC_PARAM_WEAK'?
 AWS_EXPORT(GNUTLS_SEC_PARAM_WEAK);
            ^
/home/ari_dk/gnat2018_old_ko/tarball_gnat2018/aws-gpl-2018-src/config/ssl/gnutls/wrappers.c:35:25: note: in definition of macro 'AWS_EXPORT'
    const int _AWS_##c = c;
 
....                        ^
`
Regards

**Comment by anisimkov** [comment]
AWS needs at least version 3.2.4 of GNUTLS. See readme.

**Comment by eqcola** [comment]
ok thanks

**Comment by anisimkov** [comment]
Could you pleas close the issue ?
