### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Roland4444** [AdaCore/aws#7]
Build simple program for your manual: 
http://docs.adacore.com/aws-docs/aws.pdf

One file application:
with AWS.Response;
with AWS.Server;
with AWS.Status;

procedure prog is
   WS: AWS.Server.HTTP;

   function HW_CB (Request: in AWS.Status.Data) return AWS.Response.Data is
   URI: Constant String := AWS.Status.URI (Request);
   begin
      if URI = "/hello" then return AWS.Response.Build("text/html","<p>hello world!");
      else return AWS.Response.Build("text/html","<p> Hmmm>");
      end if;
   end HW_CB;

begin
   AWS.Server.Start(WS,"hello world", Callback => HW_CB'Unrestricted_Access);
   delay 10.0;

end prog;
Build it (succesfully) when run i got error  raised AWS.NET.SOCKET_ERROR : INPUT timeout.
[2017-04-23 06:47:34] process exited with status 1, elapsed time: 00.76s

**Comment by anisimkov** [comment]
Very strange behavior. I can't reproduce it. Looks like your local
network configuration problem. You can use Start_Error routine from
AWS.Server.Log package to understand what is happening.

**Comment by anisimkov** [comment]
On 2017-04-23 07:55, Dmitriy Anisimkov wrote:
> Very strange behavior. I can't reproduce it. Looks like your local
> network configuration problem. You can use Start_Error routine from
> AWS.Server.Log package to understand what is happening.

and use -g and -bargs -E switches on build.
-g for debug information
-bargs -E for stack trace information on exceptions.

> On 2017-04-23 06:51, Roland4444 wrote:
>> : INPUT timeout.
>> [2017-04-23 06:47:34] process exited with status 1, elapsed time: 00.76s

**Comment by Roland4444** [comment]
interesting, but this error  go out. i try rebuild with ur debug options all go ok, rebuild with standart options all worked!

**Comment by Roland4444** [comment]
wanna use ur server , so will be reserach and tested all features) see u later! Nice day!
