### ISSUE TITLE
Storage_Error with large strings and websockets

### ISSUE THREAD

**Issue by briot** [AdaCore/aws#89]
When using websockets, I am getting storage_error when sending a large string (more than the 2Mb of the stack size for tasks).

Sending such a large message is not a very good idea, so we will improve things on that side, but I do not expect AWS to crash nonetheless...

Here are some details:

  - I am building my large string on the heap as a GNATCOLL.Strings.XStriing, then calling 
    AWS.Net.Websocket.Registry.Send with the string, accessed via 
    GNATCOLL.Strings.Access_String. 
   That ends up in the code path that sends the whole string as a single fragment, not the code
    path that does multiple fragments (the latter has other issues, I'll open separate Issue for that).

The backtrace I am getting is:

```
src/core/aws-translator-conversion.adb:96 (discriminator 18)
src/core/aws-translator-conversion.adb:176
src/core/aws-translator.adb:555
src/core/aws-net-websocket.adb:616 (discriminator 8)
src/core/aws-net-websocket-registry.adb:855 (discriminator 8)
src/core/aws-net-websocket-registry.adb:650
src/core/aws-net-websocket-registry.adb:1136 (discriminator 24)
websockets-send.adb:11  --  my code
```
The error occurs in the Conversion function, which has the following profile:

```
      function To_Stream_Element_Array
        (Data : String) return Stream_Element_Array
      is
         subtype Fixed_String is String (Data'First .. Data'Last);
         subtype Fixed_Array is Stream_Element_Array
           (Stream_Element_Offset (Data'First)
            .. Stream_Element_Offset (Data'Last));
         function To_Stream_Elements is
           new Ada.Unchecked_Conversion (Fixed_String, Fixed_Array);
      begin
         return To_Stream_Elements (Data);
      end To_Stream_Element_Array;
```
I must admit I am not 100% sure what happens here. Looking at the function's profile, I expect the compiler would create a copy of the array and returns that on the secondary stack. The extra copying would be inefficient, and that's suppose to be the fast path, so instead I think the compiler is just returning an address here.

But since the original string is on the heap, and the caller of To_Stream_Element_Array thinks it is
returned on the stack, I think this could explain the crash here.

**Comment by briot** [comment]
Seems like a better approach would be to return a Stream_Element_Array_Access or some such

**Comment by briot** [comment]
Is anyone actually reading these issues reported in github ? They tend to stay for a very long time un-acknowledged.

**Comment by TurboGit** [comment]
Yes, but not very actively. Note that in Convension there is a version returning a Stream_Element_Array_Access. So it may just be needed to use this.

**Comment by briot** [comment]
I am closing this issue after the work on #160. I tried to reproduce it with the following reproducer, but everything seems to work fine. There might issues if `AWS.Net.Output_Space` was returning values close to 2Mb, but this is very unlikely I think. On linux, this function returns -1 and the code then uses 100_000 when sending, but typical socket buffers are like 16kb or 32kb, nowhere close to 2Mb.

```
with AWS.Config.Set;
with AWS.Net.WebSocket.Registry.Control;
with AWS.Server.Status;
with AWS.Services.Dispatchers.URI;
with AWS.Status;

procedure Main is
   Server  : AWS.Server.HTTP;
   Handler : AWS.Services.Dispatchers.URI.Handler;

   procedure Client is
      use AWS.Net.WebSocket;
      Sock : AWS.Net.WebSocket.Object_Class;
   begin
      Sock := new AWS.Net.WebSocket.Object;  --  client-side socket
      AWS.Net.WebSocket.Connect
         (Sock.all,
          AWS.Server.Status.Local_URL (Server) & "/streams");

      --  Send a very long message
      Sock.Send (String'(1 .. 3_000_000 => 'A'));

      delay 3.0;

      Sock.Close ("no longer needed");
   end Client;

   function Create_Socket
     (Request : AWS.Status.Data) return AWS.Net.WebSocket.Object_Class is
   begin
      return new AWS.Net.WebSocket.Object;  --  server-side socket
   end Create_Socket;

   procedure Start_Server is
      Conf    : AWS.Config.Object := AWS.Config.Get_Current;
   begin
      AWS.Config.Set.Reuse_Address (Conf, True);
      AWS.Net.WebSocket.Registry.Register
         ("/streams", Create_Socket'Unrestricted_Access);
      AWS.Server.Start
         (Web_Server => Server,
          Config     => Conf,
          Dispatcher => Handler);
      AWS.Net.WebSocket.Registry.Control.Start;
   end Start_Server;

begin
   Start_Server;
   Client;
   AWS.Net.WebSocket.Registry.Control.Shutdown;
   AWS.Server.Shutdown (Server);
end Main;
```
